[versions]
android-plugin = "7.3.0"
androidx-activity = "1.6.0"
androidx-appcompat = "1.5.1"
androidx-compose = "1.3.0-rc01"
androidx-compose-compiler = "1.3.2"
androidx-core = "1.9.0"
androidx-core-role = "1.0.0"
androidx-room = "2.4.3"
androidx-tv = "1.0.0-alpha01"
androidx-tvprovider = "1.1.0-alpha01"
coil = "2.2.2"
koin = "3.2.2"
koin-compose = "3.2.1"
kotlin = "1.7.20"
kotlin-ksp = "1.7.20-1.0.6"

[plugins]
android-app = { id = "com.android.application", version.ref = "android-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "kotlin-ksp" }

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidx.compose" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "androidx.compose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx.compose" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-core-role = { module = "androidx.core:core-role", version.ref = "androidx-core-role" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-tv-foundation = { module = "androidx.tv:tv-foundation", version.ref = "androidx.tv" }
androidx-tv-material = { module = "androidx.tv:tv-material", version.ref = "androidx.tv" }
androidx-tvprovider = { module = "androidx.tvprovider:tvprovider", version.ref = "androidx-tvprovider" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin-compose" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }

[bundles]
androidx-compose = [
    "androidx-tv-foundation",
    "androidx-tv-material",
]
androidx-tv = [
    "androidx-activity-compose",
    "androidx-compose-foundation",
    "androidx-compose-material",
    "androidx-compose-ui-tooling",
]
koin = [
    "koin-core",
    "koin-android",
    "koin-androidx-compose",
]
