[versions]
android-plugin = "8.7.1"
androidx-activity = "1.9.3"
androidx-appcompat = "1.7.0"
androidx-compose-foundation = "1.7.4"
androidx-compose-ui = "1.7.4"
androidx-core = "1.13.1"
androidx-core-role = "1.0.0"
androidx-palette = "1.0.0"
androidx-tv = "1.0.0"
androidx-tvprovider = "1.1.0-alpha01"
coil = "2.7.0"
koin-android = "4.0.0"
koin-compose = "4.0.0"
kotlin = "2.0.21"
sqldelight = "2.0.2"
timber = "5.0.1"

[plugins]
android-app = { id = "com.android.application", version.ref = "android-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidx-compose-foundation" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose-ui" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx-compose-ui" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-core-role = { module = "androidx.core:core-role", version.ref = "androidx-core-role" }
androidx-palette = { module = "androidx.palette:palette-ktx", version.ref = "androidx-palette" }
androidx-tv-material = { module = "androidx.tv:tv-material", version.ref = "androidx-tv" }
androidx-tvprovider = { module = "androidx.tvprovider:tvprovider", version.ref = "androidx-tvprovider" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin-android" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin-compose" }
sqldelight-android = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-coroutines = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqldelight" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
