[versions]
android-compileSdk = "36"
android-minSdk = "23"
android-plugin = "9.0.0"
android-targetSdk = "36"
androidx-activity = "1.12.3"
androidx-appcompat = "1.7.1"
androidx-compose-foundation = "1.10.2"
androidx-compose-runtime = "1.10.2"
androidx-compose-ui = "1.10.2"
androidx-core = "1.17.0"
androidx-core-role = "1.1.0"
androidx-navigation3 = "1.0.0"
androidx-palette = "1.0.0"
androidx-savedstate = "1.4.0"
androidx-tv = "1.0.1"
androidx-tvprovider = "1.1.0"
coil = "2.7.0"
java-jdk = "21"
koin-android = "4.1.1"
koin-compose = "4.1.1"
kotlin = "2.3.10"
kotlinx-serialization = "1.10.0"
sqldelight = "2.2.1"
timber = "5.0.1"

[plugins]
android-app = { id = "com.android.application", version.ref = "android-plugin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }

[libraries]
androidx-activity = { module = "androidx.activity:activity", version.ref = "androidx-activity" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidx-compose-foundation" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "androidx-compose-runtime" }
androidx-compose-runtime-savable = { module = "androidx.compose.runtime:runtime-saveable", version.ref = "androidx-compose-runtime" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose-ui" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose-ui" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx-compose-ui" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-core-role = { module = "androidx.core:core-role", version.ref = "androidx-core-role" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "androidx-navigation3" }
androidx-palette = { module = "androidx.palette:palette-ktx", version.ref = "androidx-palette" }
androidx-savedstate = { module = "androidx.savedstate:savedstate", version.ref = "androidx-savedstate" }
androidx-tv-material = { module = "androidx.tv:tv-material", version.ref = "androidx-tv" }
androidx-tvprovider = { module = "androidx.tvprovider:tvprovider", version.ref = "androidx-tvprovider" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin-android" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin-compose" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
sqldelight-android = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-coroutines = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqldelight" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

[bundles]
androidx-compose = [
    "androidx-compose-foundation",
    "androidx-compose-runtime",
    "androidx-compose-runtime-savable",
    "androidx-compose-ui",
    "androidx-compose-ui-tooling-preview",
]
androidx-core = [
    "androidx-core",
    "androidx-core-role",
]
koin = [
    "koin-android",
    "koin-androidx-compose",
]
sqldelight = [
    "sqldelight-android",
    "sqldelight-coroutines",
]
