[versions]
android-plugin = "8.1.0"
androidx-activity = "1.7.2"
androidx-appcompat = "1.6.1"
androidx-compose-compiler = "1.5.1"
androidx-compose-foundation = "1.6.0-alpha03"
androidx-compose-material3 = "1.2.0-alpha05"
androidx-compose-ui = "1.6.0-alpha03"
androidx-core = "1.10.1"
androidx-core-role = "1.0.0"
androidx-room = "2.5.2"
androidx-tv = "1.0.0-alpha08"
androidx-tvprovider = "1.1.0-alpha01"
coil = "2.4.0"
koin-android = "3.4.3"
koin-compose = "3.4.6"
kotlin = "1.9.0"
kotlin-ksp = "1.9.0-1.0.13"
timber = "5.0.1"

[plugins]
android-app = { id = "com.android.application", version.ref = "android-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "kotlin-ksp" }

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "androidx-compose-compiler" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidx-compose-foundation" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidx-compose-material3" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose-ui" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx-compose-ui" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-core-role = { module = "androidx.core:core-role", version.ref = "androidx-core-role" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-tv-foundation = { module = "androidx.tv:tv-foundation", version.ref = "androidx-tv" }
androidx-tv-material = { module = "androidx.tv:tv-material", version.ref = "androidx.tv" }
androidx-tvprovider = { module = "androidx.tvprovider:tvprovider", version.ref = "androidx-tvprovider" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin-android" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin-compose" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
